-- Coach Console seed data. Safe to re-run.
begin;

-- Exercise library
insert into exercises (slug, name, pattern, primary_muscles, equipment, contraindications, is_compound) values
('wall_sit', 'Wall Sit', 'squat', array['quads']::text[], array['bodyweight']::text[], array[]::text[], false),
('box_squat_bw', 'Bodyweight Box Squat', 'squat', array['quads','glutes']::text[], array['box']::text[], array[]::text[], true),
('bodyweight_squat', 'Bodyweight Squat', 'squat', array['quads','glutes']::text[], array['bodyweight']::text[], array[]::text[], true),
('tempo_bodyweight_squat', 'Tempo Bodyweight Squat (slow lower)', 'squat', array['quads','glutes']::text[], array['bodyweight']::text[], array[]::text[], true),
('single_leg_box_squat', 'Single-Leg Box Squat', 'squat', array['quads','glutes']::text[], array['box']::text[], array['knee']::text[], true),
('goblet_box_squat', 'Goblet Box Squat', 'squat', array['quads','glutes']::text[], array['dumbbell','box']::text[], array[]::text[], true),
('goblet_squat', 'Goblet Squat', 'squat', array['quads','glutes']::text[], array['dumbbell']::text[], array[]::text[], true),
('heels_elevated_goblet_squat', 'Heels-Elevated Goblet Squat', 'squat', array['quads']::text[], array['dumbbell']::text[], array['knee']::text[], true),
('db_front_squat', 'Dumbbell Front Squat', 'squat', array['quads','glutes']::text[], array['dumbbell']::text[], array[]::text[], true),
('barbell_box_squat', 'Barbell Box Squat', 'squat', array['quads','glutes']::text[], array['barbell','box']::text[], array['low_back']::text[], true),
('barbell_back_squat', 'Barbell Back Squat', 'squat', array['quads','glutes','adductors']::text[], array['barbell']::text[], array['low_back','knee']::text[], true),
('pause_back_squat', 'Pause Back Squat', 'squat', array['quads','glutes']::text[], array['barbell']::text[], array['low_back','knee']::text[], true),
('barbell_front_squat', 'Barbell Front Squat', 'squat', array['quads','glutes']::text[], array['barbell']::text[], array['wrist','knee']::text[], true),
('leg_press', 'Leg Press', 'squat', array['quads','glutes']::text[], array['machine']::text[], array[]::text[], true),
('hack_squat', 'Hack Squat', 'squat', array['quads']::text[], array['machine']::text[], array['knee']::text[], true),
('glute_bridge', 'Glute Bridge', 'hinge', array['glutes','hamstrings']::text[], array['bodyweight']::text[], array[]::text[], false),
('single_leg_glute_bridge', 'Single-Leg Glute Bridge', 'hinge', array['glutes','hamstrings']::text[], array['bodyweight']::text[], array[]::text[], false),
('hip_hinge_drill', 'Hip Hinge Drill (dowel/broomstick)', 'hinge', array['hamstrings','glutes']::text[], array['bodyweight']::text[], array[]::text[], true),
('single_leg_rdl_bw', 'Single-Leg RDL (bodyweight)', 'hinge', array['hamstrings','glutes']::text[], array['bodyweight']::text[], array[]::text[], true),
('band_good_morning', 'Band Good Morning', 'hinge', array['hamstrings','glutes']::text[], array['band']::text[], array[]::text[], true),
('db_romanian_deadlift', 'Dumbbell Romanian Deadlift', 'hinge', array['hamstrings','glutes']::text[], array['dumbbell']::text[], array['low_back']::text[], true),
('db_single_leg_rdl', 'Dumbbell Single-Leg RDL', 'hinge', array['hamstrings','glutes']::text[], array['dumbbell']::text[], array[]::text[], true),
('db_hip_thrust', 'Dumbbell Hip Thrust', 'hinge', array['glutes']::text[], array['dumbbell','bench']::text[], array[]::text[], true),
('barbell_hip_thrust', 'Barbell Hip Thrust', 'hinge', array['glutes']::text[], array['barbell','bench']::text[], array[]::text[], true),
('kb_deadlift', 'Kettlebell Deadlift', 'hinge', array['glutes','hamstrings']::text[], array['kettlebell']::text[], array[]::text[], true),
('kb_swing', 'Kettlebell Swing', 'hinge', array['glutes','hamstrings']::text[], array['kettlebell']::text[], array['low_back']::text[], true),
('cable_pull_through', 'Cable Pull-Through', 'hinge', array['glutes','hamstrings']::text[], array['cable']::text[], array[]::text[], true),
('barbell_rdl', 'Barbell Romanian Deadlift', 'hinge', array['hamstrings','glutes']::text[], array['barbell']::text[], array['low_back']::text[], true),
('trap_bar_deadlift', 'Trap-Bar Deadlift', 'hinge', array['glutes','quads','hamstrings']::text[], array['barbell']::text[], array['low_back']::text[], true),
('conventional_deadlift', 'Conventional Deadlift', 'hinge', array['glutes','hamstrings','back']::text[], array['barbell']::text[], array['low_back']::text[], true),
('back_extension', 'Back Extension (45°)', 'hinge', array['glutes','hamstrings','erectors']::text[], array['machine']::text[], array['low_back']::text[], false),
('supported_split_squat', 'Supported Split Squat', 'lunge', array['quads','glutes']::text[], array['bodyweight']::text[], array[]::text[], true),
('split_squat_bw', 'Split Squat (bodyweight)', 'lunge', array['quads','glutes']::text[], array['bodyweight']::text[], array['knee']::text[], true),
('reverse_lunge_bw', 'Reverse Lunge (bodyweight)', 'lunge', array['quads','glutes']::text[], array['bodyweight']::text[], array['knee']::text[], true),
('walking_lunge_bw', 'Walking Lunge (bodyweight)', 'lunge', array['quads','glutes']::text[], array['bodyweight']::text[], array['knee']::text[], true),
('bulgarian_split_squat_bw', 'Rear-Foot-Elevated Split Squat (bodyweight)', 'lunge', array['quads','glutes']::text[], array['box']::text[], array['knee']::text[], true),
('step_up_bw', 'Step-Up (bodyweight)', 'lunge', array['quads','glutes']::text[], array['box']::text[], array[]::text[], true),
('lateral_lunge_bw', 'Lateral Lunge (bodyweight)', 'lunge', array['adductors','glutes','quads']::text[], array['bodyweight']::text[], array['knee']::text[], true),
('db_split_squat', 'Dumbbell Split Squat', 'lunge', array['quads','glutes']::text[], array['dumbbell']::text[], array[]::text[], true),
('db_bulgarian_split_squat', 'Dumbbell Rear-Foot-Elevated Split Squat', 'lunge', array['quads','glutes']::text[], array['dumbbell','box']::text[], array['knee']::text[], true),
('db_reverse_lunge', 'Dumbbell Reverse Lunge', 'lunge', array['quads','glutes']::text[], array['dumbbell']::text[], array['knee']::text[], true),
('db_walking_lunge', 'Dumbbell Walking Lunge', 'lunge', array['quads','glutes']::text[], array['dumbbell']::text[], array['knee']::text[], true),
('db_step_up', 'Dumbbell Step-Up', 'lunge', array['quads','glutes']::text[], array['dumbbell','box']::text[], array[]::text[], true),
('db_lateral_lunge', 'Goblet Lateral Lunge', 'lunge', array['adductors','glutes','quads']::text[], array['dumbbell']::text[], array['knee']::text[], true),
('barbell_reverse_lunge', 'Barbell Reverse Lunge', 'lunge', array['quads','glutes']::text[], array['barbell']::text[], array['knee']::text[], true),
('wall_push_up', 'Wall Push-Up', 'horizontal_push', array['chest','triceps']::text[], array['bodyweight']::text[], array[]::text[], true),
('incline_push_up', 'Incline Push-Up', 'horizontal_push', array['chest','triceps']::text[], array['box']::text[], array['wrist']::text[], true),
('push_up', 'Push-Up', 'horizontal_push', array['chest','triceps','shoulders']::text[], array['bodyweight']::text[], array['wrist','shoulder']::text[], true),
('decline_push_up', 'Decline Push-Up', 'horizontal_push', array['chest','shoulders']::text[], array['box']::text[], array['wrist','shoulder']::text[], true),
('band_chest_press', 'Band Chest Press', 'horizontal_push', array['chest','triceps']::text[], array['band']::text[], array[]::text[], true),
('db_floor_press', 'Dumbbell Floor Press', 'horizontal_push', array['chest','triceps']::text[], array['dumbbell']::text[], array[]::text[], true),
('db_bench_press', 'Dumbbell Bench Press', 'horizontal_push', array['chest','triceps','shoulders']::text[], array['dumbbell','bench']::text[], array['shoulder']::text[], true),
('db_incline_press', 'Dumbbell Incline Press', 'horizontal_push', array['upper chest','shoulders']::text[], array['dumbbell','bench']::text[], array['shoulder']::text[], true),
('machine_chest_press', 'Machine Chest Press', 'horizontal_push', array['chest','triceps']::text[], array['machine']::text[], array[]::text[], true),
('barbell_bench_press', 'Barbell Bench Press', 'horizontal_push', array['chest','triceps','shoulders']::text[], array['barbell','bench']::text[], array['shoulder']::text[], true),
('pause_bench_press', 'Pause Bench Press', 'horizontal_push', array['chest','triceps']::text[], array['barbell','bench']::text[], array['shoulder']::text[], true),
('wall_slide', 'Wall Slide', 'vertical_push', array['serratus','lower traps']::text[], array['bodyweight']::text[], array[]::text[], false),
('band_overhead_press', 'Band Overhead Press', 'vertical_push', array['shoulders','triceps']::text[], array['band']::text[], array[]::text[], true),
('incline_pike_push_up', 'Incline Pike Push-Up', 'vertical_push', array['shoulders','triceps']::text[], array['box']::text[], array['shoulder','wrist']::text[], true),
('pike_push_up', 'Pike Push-Up', 'vertical_push', array['shoulders','triceps']::text[], array['bodyweight']::text[], array['shoulder','wrist']::text[], true),
('half_kneeling_db_press', 'Half-Kneeling Single-Arm DB Press', 'vertical_push', array['shoulders','triceps','core']::text[], array['dumbbell']::text[], array['shoulder']::text[], true),
('seated_db_overhead_press', 'Seated Dumbbell Overhead Press', 'vertical_push', array['shoulders','triceps']::text[], array['dumbbell','bench']::text[], array['shoulder']::text[], true),
('standing_db_overhead_press', 'Standing Dumbbell Overhead Press', 'vertical_push', array['shoulders','triceps']::text[], array['dumbbell']::text[], array['shoulder']::text[], true),
('landmine_press', 'Landmine Press', 'vertical_push', array['shoulders','upper chest']::text[], array['barbell']::text[], array[]::text[], true),
('machine_shoulder_press', 'Machine Shoulder Press', 'vertical_push', array['shoulders','triceps']::text[], array['machine']::text[], array['shoulder']::text[], true),
('barbell_overhead_press', 'Barbell Overhead Press', 'vertical_push', array['shoulders','triceps']::text[], array['barbell']::text[], array['shoulder','low_back']::text[], true),
('door_frame_row', 'Door-Frame Row', 'horizontal_pull', array['lats','rhomboids']::text[], array['bodyweight']::text[], array[]::text[], true),
('band_row', 'Band Row', 'horizontal_pull', array['lats','rhomboids']::text[], array['band']::text[], array[]::text[], true),
('chest_supported_db_row', 'Chest-Supported Dumbbell Row', 'horizontal_pull', array['lats','rhomboids','rear delts']::text[], array['dumbbell','bench']::text[], array[]::text[], true),
('one_arm_db_row', 'One-Arm Dumbbell Row', 'horizontal_pull', array['lats','rhomboids']::text[], array['dumbbell','bench']::text[], array[]::text[], true),
('db_bent_over_row', 'Dumbbell Bent-Over Row', 'horizontal_pull', array['lats','rhomboids']::text[], array['dumbbell']::text[], array['low_back']::text[], true),
('machine_row', 'Machine Row', 'horizontal_pull', array['lats','rhomboids']::text[], array['machine']::text[], array[]::text[], true),
('seated_cable_row', 'Seated Cable Row', 'horizontal_pull', array['lats','rhomboids']::text[], array['cable']::text[], array[]::text[], true),
('inverted_row', 'Inverted Row (bar in rack)', 'horizontal_pull', array['lats','rhomboids','biceps']::text[], array['barbell']::text[], array[]::text[], true),
('barbell_row', 'Barbell Bent-Over Row', 'horizontal_pull', array['lats','rhomboids','erectors']::text[], array['barbell']::text[], array['low_back']::text[], true),
('face_pull', 'Cable Face Pull', 'horizontal_pull', array['rear delts','rotator cuff']::text[], array['cable']::text[], array[]::text[], false),
('band_pull_apart', 'Band Pull-Apart', 'horizontal_pull', array['rear delts','rhomboids']::text[], array['band']::text[], array[]::text[], false),
('prone_ytw', 'Prone Y-T-W Raise', 'vertical_pull', array['lower traps','rear delts']::text[], array['bodyweight']::text[], array[]::text[], false),
('band_lat_pulldown', 'Band Lat Pulldown', 'vertical_pull', array['lats']::text[], array['band']::text[], array[]::text[], true),
('lat_pulldown', 'Lat Pulldown', 'vertical_pull', array['lats','biceps']::text[], array['cable']::text[], array[]::text[], true),
('assisted_pull_up', 'Assisted Pull-Up (machine)', 'vertical_pull', array['lats','biceps']::text[], array['machine']::text[], array[]::text[], true),
('band_assisted_pull_up', 'Band-Assisted Pull-Up', 'vertical_pull', array['lats','biceps']::text[], array['band','pullup_bar']::text[], array[]::text[], true),
('negative_pull_up', 'Negative (Eccentric) Pull-Up', 'vertical_pull', array['lats','biceps']::text[], array['pullup_bar']::text[], array['elbow']::text[], true),
('pull_up', 'Pull-Up', 'vertical_pull', array['lats','biceps']::text[], array['pullup_bar']::text[], array['shoulder','elbow']::text[], true),
('chin_up', 'Chin-Up', 'vertical_pull', array['lats','biceps']::text[], array['pullup_bar']::text[], array['elbow']::text[], true),
('straight_arm_pulldown', 'Straight-Arm Cable Pulldown', 'vertical_pull', array['lats']::text[], array['cable']::text[], array[]::text[], false),
('db_pullover', 'Dumbbell Pullover', 'vertical_pull', array['lats','chest']::text[], array['dumbbell','bench']::text[], array['shoulder']::text[], false),
('dead_bug', 'Dead Bug', 'core_anti_extension', array['deep core']::text[], array['bodyweight']::text[], array[]::text[], false),
('incline_plank', 'Incline Plank (hands on bench)', 'core_anti_extension', array['core']::text[], array['box']::text[], array[]::text[], false),
('forearm_plank', 'Forearm Plank', 'core_anti_extension', array['core']::text[], array['bodyweight']::text[], array[]::text[], false),
('long_lever_plank', 'Long-Lever Plank', 'core_anti_extension', array['core']::text[], array['bodyweight']::text[], array['low_back']::text[], false),
('hollow_body_hold', 'Hollow Body Hold', 'core_anti_extension', array['core']::text[], array['bodyweight']::text[], array['low_back']::text[], false),
('bird_dog', 'Bird Dog', 'core_anti_rotation', array['core','glutes']::text[], array['bodyweight']::text[], array[]::text[], false),
('side_plank_knees', 'Side Plank (knees)', 'core_anti_rotation', array['obliques']::text[], array['bodyweight']::text[], array[]::text[], false),
('side_plank', 'Side Plank', 'core_anti_rotation', array['obliques']::text[], array['bodyweight']::text[], array['shoulder']::text[], false),
('plank_shoulder_tap', 'Plank Shoulder Tap', 'core_anti_rotation', array['core']::text[], array['bodyweight']::text[], array['wrist']::text[], false),
('band_pallof_press', 'Band Pallof Press', 'core_anti_rotation', array['obliques','core']::text[], array['band']::text[], array[]::text[], false),
('pallof_press', 'Cable Pallof Press', 'core_anti_rotation', array['obliques','core']::text[], array['cable']::text[], array[]::text[], false),
('cable_woodchop', 'Cable Woodchop', 'core_anti_rotation', array['obliques']::text[], array['cable']::text[], array['low_back']::text[], false),
('reverse_crunch', 'Reverse Crunch', 'core_flexion', array['abs']::text[], array['bodyweight']::text[], array[]::text[], false),
('hanging_knee_raise', 'Hanging Knee Raise', 'core_flexion', array['abs','hip flexors']::text[], array['pullup_bar']::text[], array['shoulder']::text[], false),
('farmer_carry', 'Farmer Carry', 'carry', array['grip','traps','core']::text[], array['dumbbell']::text[], array[]::text[], true),
('suitcase_carry', 'Suitcase Carry', 'carry', array['obliques','grip']::text[], array['dumbbell']::text[], array[]::text[], true),
('kb_goblet_carry', 'Goblet Carry', 'carry', array['core','upper back']::text[], array['kettlebell']::text[], array[]::text[], true),
('band_curl', 'Band Biceps Curl', 'isolation_arms', array['biceps']::text[], array['band']::text[], array[]::text[], false),
('db_biceps_curl', 'Dumbbell Biceps Curl', 'isolation_arms', array['biceps']::text[], array['dumbbell']::text[], array[]::text[], false),
('hammer_curl', 'Hammer Curl', 'isolation_arms', array['biceps','brachialis']::text[], array['dumbbell']::text[], array[]::text[], false),
('cable_curl', 'Cable Curl', 'isolation_arms', array['biceps']::text[], array['cable']::text[], array[]::text[], false),
('barbell_curl', 'Barbell Curl', 'isolation_arms', array['biceps']::text[], array['barbell']::text[], array['elbow','wrist']::text[], false),
('band_triceps_pushdown', 'Band Triceps Pushdown', 'isolation_arms', array['triceps']::text[], array['band']::text[], array[]::text[], false),
('cable_triceps_pushdown', 'Cable Triceps Pushdown', 'isolation_arms', array['triceps']::text[], array['cable']::text[], array[]::text[], false),
('db_overhead_triceps_extension', 'Dumbbell Overhead Triceps Extension', 'isolation_arms', array['triceps']::text[], array['dumbbell']::text[], array['elbow','shoulder']::text[], false),
('db_skull_crusher', 'Dumbbell Skull Crusher', 'isolation_arms', array['triceps']::text[], array['dumbbell','bench']::text[], array['elbow']::text[], false),
('bench_dip', 'Bench Dip', 'isolation_arms', array['triceps']::text[], array['box']::text[], array['shoulder','wrist']::text[], false),
('band_lateral_raise', 'Band Lateral Raise', 'isolation_shoulders', array['side delts']::text[], array['band']::text[], array[]::text[], false),
('db_lateral_raise', 'Dumbbell Lateral Raise', 'isolation_shoulders', array['side delts']::text[], array['dumbbell']::text[], array['shoulder']::text[], false),
('cable_lateral_raise', 'Cable Lateral Raise', 'isolation_shoulders', array['side delts']::text[], array['cable']::text[], array['shoulder']::text[], false),
('db_rear_delt_fly', 'Dumbbell Rear-Delt Fly', 'isolation_shoulders', array['rear delts']::text[], array['dumbbell']::text[], array[]::text[], false),
('db_chest_fly', 'Dumbbell Chest Fly', 'isolation_chest', array['chest']::text[], array['dumbbell','bench']::text[], array['shoulder']::text[], false),
('cable_chest_fly', 'Cable Chest Fly', 'isolation_chest', array['chest']::text[], array['cable']::text[], array['shoulder']::text[], false),
('leg_extension', 'Leg Extension', 'isolation_legs', array['quads']::text[], array['machine']::text[], array['knee']::text[], false),
('lying_leg_curl', 'Lying Leg Curl', 'isolation_legs', array['hamstrings']::text[], array['machine']::text[], array[]::text[], false),
('stability_ball_leg_curl', 'Slider/Towel Leg Curl', 'isolation_legs', array['hamstrings']::text[], array['bodyweight']::text[], array[]::text[], false),
('calf_raise_bw', 'Standing Calf Raise (bodyweight)', 'isolation_legs', array['calves']::text[], array['bodyweight']::text[], array[]::text[], false),
('db_calf_raise', 'Dumbbell Calf Raise', 'isolation_legs', array['calves']::text[], array['dumbbell']::text[], array[]::text[], false),
('machine_calf_raise', 'Machine Calf Raise', 'isolation_legs', array['calves']::text[], array['machine']::text[], array[]::text[], false),
('band_lateral_walk', 'Band Lateral Walk', 'isolation_legs', array['glute med']::text[], array['band']::text[], array[]::text[], false),
('squat_jump', 'Squat Jump', 'power', array['quads','glutes']::text[], array['bodyweight']::text[], array['knee','ankle']::text[], true),
('box_jump', 'Box Jump (step down)', 'power', array['quads','glutes']::text[], array['box']::text[], array['knee','ankle']::text[], true),
('broad_jump', 'Broad Jump', 'power', array['glutes','quads']::text[], array['bodyweight']::text[], array['knee','ankle']::text[], true),
('lateral_bound', 'Lateral Bound', 'power', array['glutes','adductors']::text[], array['bodyweight']::text[], array['knee','ankle']::text[], true),
('plyo_push_up', 'Plyometric Push-Up', 'power', array['chest','triceps']::text[], array['bodyweight']::text[], array['wrist','shoulder']::text[], true),
('med_ball_chest_pass', 'Medicine Ball Chest Pass', 'power', array['chest','triceps']::text[], array['medicine_ball']::text[], array[]::text[], true),
('med_ball_slam', 'Medicine Ball Slam', 'power', array['lats','core']::text[], array['medicine_ball']::text[], array['low_back','shoulder']::text[], true),
('med_ball_rotational_throw', 'Medicine Ball Rotational Throw', 'power', array['obliques','hips']::text[], array['medicine_ball']::text[], array['low_back']::text[], true),
('push_press', 'Push Press', 'power', array['shoulders','legs']::text[], array['barbell']::text[], array['shoulder','low_back']::text[], true),
('hang_power_clean', 'Hang Power Clean', 'power', array['posterior chain','traps']::text[], array['barbell']::text[], array['wrist','low_back','shoulder']::text[], true),
('cat_cow', 'Cat-Cow', 'mobility', array['spine']::text[], array['bodyweight']::text[], array[]::text[], false),
('worlds_greatest_stretch', 'World''s Greatest Stretch', 'mobility', array['hips','t-spine']::text[], array['bodyweight']::text[], array[]::text[], false),
('hip_90_90', '90/90 Hip Switch', 'mobility', array['hips']::text[], array['bodyweight']::text[], array['hip']::text[], false),
('open_book', 'Thoracic Open Book', 'mobility', array['t-spine']::text[], array['bodyweight']::text[], array[]::text[], false),
('couch_stretch', 'Half-Kneeling Hip Flexor Stretch', 'mobility', array['hip flexors','quads']::text[], array['bodyweight']::text[], array['knee']::text[], false),
('childs_pose', 'Child''s Pose', 'mobility', array['lats','low back']::text[], array['bodyweight']::text[], array['knee']::text[], false),
('ankle_rocks', 'Knee-to-Wall Ankle Rocks', 'mobility', array['ankles']::text[], array['bodyweight']::text[], array[]::text[], false),
('deep_squat_hold', 'Supported Deep Squat Hold', 'mobility', array['hips','ankles']::text[], array['bodyweight']::text[], array['knee']::text[], false),
('thread_the_needle', 'Thread the Needle', 'mobility', array['t-spine','shoulders']::text[], array['bodyweight']::text[], array[]::text[], false),
('band_shoulder_pass', 'Band Shoulder Pass-Through', 'mobility', array['shoulders']::text[], array['band']::text[], array['shoulder']::text[], false),
('doorway_pec_stretch', 'Doorway Pec Stretch', 'mobility', array['chest']::text[], array['bodyweight']::text[], array['shoulder']::text[], false),
('supine_hamstring_stretch', 'Supine Hamstring Stretch', 'mobility', array['hamstrings']::text[], array['bodyweight']::text[], array[]::text[], false),
('figure_four_stretch', 'Figure-4 Glute Stretch', 'mobility', array['glutes']::text[], array['bodyweight']::text[], array['hip']::text[], false),
('neck_cars', 'Neck Controlled Rotations', 'mobility', array['neck']::text[], array['bodyweight']::text[], array['neck']::text[], false)
on conflict (slug) do update set name = excluded.name, pattern = excluded.pattern, primary_muscles = excluded.primary_muscles, equipment = excluded.equipment, contraindications = excluded.contraindications, is_compound = excluded.is_compound;

-- Regression / progression links
update exercises e set regression_id = r.id, progression_id = p.id from (values
('wall_sit', null, 'box_squat_bw'),
('box_squat_bw', 'wall_sit', 'bodyweight_squat'),
('bodyweight_squat', 'box_squat_bw', 'tempo_bodyweight_squat'),
('tempo_bodyweight_squat', 'bodyweight_squat', 'single_leg_box_squat'),
('single_leg_box_squat', 'tempo_bodyweight_squat', null),
('goblet_box_squat', 'box_squat_bw', 'goblet_squat'),
('goblet_squat', 'goblet_box_squat', 'heels_elevated_goblet_squat'),
('heels_elevated_goblet_squat', 'goblet_squat', 'db_front_squat'),
('db_front_squat', 'goblet_squat', null),
('barbell_box_squat', 'goblet_squat', 'barbell_back_squat'),
('barbell_back_squat', 'barbell_box_squat', 'pause_back_squat'),
('pause_back_squat', 'barbell_back_squat', null),
('barbell_front_squat', 'goblet_squat', null),
('leg_press', 'goblet_box_squat', 'barbell_back_squat'),
('hack_squat', 'leg_press', null),
('glute_bridge', null, 'single_leg_glute_bridge'),
('single_leg_glute_bridge', 'glute_bridge', 'db_hip_thrust'),
('hip_hinge_drill', null, 'db_romanian_deadlift'),
('single_leg_rdl_bw', 'hip_hinge_drill', 'db_single_leg_rdl'),
('band_good_morning', 'hip_hinge_drill', 'db_romanian_deadlift'),
('db_romanian_deadlift', 'hip_hinge_drill', 'db_single_leg_rdl'),
('db_single_leg_rdl', 'db_romanian_deadlift', null),
('db_hip_thrust', 'glute_bridge', 'barbell_hip_thrust'),
('barbell_hip_thrust', 'db_hip_thrust', null),
('kb_deadlift', 'hip_hinge_drill', 'kb_swing'),
('kb_swing', 'kb_deadlift', null),
('cable_pull_through', 'hip_hinge_drill', 'barbell_rdl'),
('barbell_rdl', 'db_romanian_deadlift', 'conventional_deadlift'),
('trap_bar_deadlift', 'kb_deadlift', 'conventional_deadlift'),
('conventional_deadlift', 'trap_bar_deadlift', null),
('back_extension', 'glute_bridge', null),
('supported_split_squat', null, 'split_squat_bw'),
('split_squat_bw', 'supported_split_squat', 'reverse_lunge_bw'),
('reverse_lunge_bw', 'split_squat_bw', 'walking_lunge_bw'),
('walking_lunge_bw', 'reverse_lunge_bw', 'bulgarian_split_squat_bw'),
('bulgarian_split_squat_bw', 'split_squat_bw', 'db_bulgarian_split_squat'),
('step_up_bw', null, 'db_step_up'),
('lateral_lunge_bw', 'supported_split_squat', 'db_lateral_lunge'),
('db_split_squat', 'split_squat_bw', 'db_bulgarian_split_squat'),
('db_bulgarian_split_squat', 'db_split_squat', null),
('db_reverse_lunge', 'reverse_lunge_bw', 'db_walking_lunge'),
('db_walking_lunge', 'db_reverse_lunge', null),
('db_step_up', 'step_up_bw', null),
('db_lateral_lunge', 'lateral_lunge_bw', null),
('barbell_reverse_lunge', 'db_reverse_lunge', null),
('wall_push_up', null, 'incline_push_up'),
('incline_push_up', 'wall_push_up', 'push_up'),
('push_up', 'incline_push_up', 'decline_push_up'),
('decline_push_up', 'push_up', null),
('band_chest_press', 'wall_push_up', 'push_up'),
('db_floor_press', 'incline_push_up', 'db_bench_press'),
('db_bench_press', 'db_floor_press', 'db_incline_press'),
('db_incline_press', 'db_bench_press', 'barbell_bench_press'),
('machine_chest_press', 'incline_push_up', 'db_bench_press'),
('barbell_bench_press', 'db_bench_press', 'pause_bench_press'),
('pause_bench_press', 'barbell_bench_press', null),
('wall_slide', null, 'band_overhead_press'),
('band_overhead_press', 'wall_slide', 'half_kneeling_db_press'),
('incline_pike_push_up', 'wall_slide', 'pike_push_up'),
('pike_push_up', 'incline_pike_push_up', null),
('half_kneeling_db_press', 'band_overhead_press', 'seated_db_overhead_press'),
('seated_db_overhead_press', 'half_kneeling_db_press', 'standing_db_overhead_press'),
('standing_db_overhead_press', 'seated_db_overhead_press', 'barbell_overhead_press'),
('landmine_press', 'half_kneeling_db_press', 'barbell_overhead_press'),
('machine_shoulder_press', 'band_overhead_press', 'seated_db_overhead_press'),
('barbell_overhead_press', 'standing_db_overhead_press', 'push_press'),
('door_frame_row', null, 'band_row'),
('band_row', 'door_frame_row', 'chest_supported_db_row'),
('chest_supported_db_row', 'band_row', 'one_arm_db_row'),
('one_arm_db_row', 'chest_supported_db_row', 'db_bent_over_row'),
('db_bent_over_row', 'one_arm_db_row', null),
('machine_row', 'band_row', 'seated_cable_row'),
('seated_cable_row', 'machine_row', 'barbell_row'),
('inverted_row', 'seated_cable_row', null),
('barbell_row', 'seated_cable_row', null),
('face_pull', 'band_pull_apart', null),
('band_pull_apart', null, 'face_pull'),
('prone_ytw', null, 'band_lat_pulldown'),
('band_lat_pulldown', 'prone_ytw', 'lat_pulldown'),
('lat_pulldown', 'band_lat_pulldown', 'assisted_pull_up'),
('assisted_pull_up', 'lat_pulldown', 'pull_up'),
('band_assisted_pull_up', 'band_lat_pulldown', 'negative_pull_up'),
('negative_pull_up', 'band_assisted_pull_up', 'pull_up'),
('pull_up', 'negative_pull_up', 'chin_up'),
('chin_up', 'negative_pull_up', null),
('straight_arm_pulldown', 'band_lat_pulldown', null),
('db_pullover', null, null),
('dead_bug', null, 'incline_plank'),
('incline_plank', 'dead_bug', 'forearm_plank'),
('forearm_plank', 'incline_plank', 'long_lever_plank'),
('long_lever_plank', 'forearm_plank', 'hollow_body_hold'),
('hollow_body_hold', 'dead_bug', null),
('bird_dog', null, 'plank_shoulder_tap'),
('side_plank_knees', null, 'side_plank'),
('side_plank', 'side_plank_knees', null),
('plank_shoulder_tap', 'forearm_plank', null),
('band_pallof_press', 'bird_dog', 'pallof_press'),
('pallof_press', 'band_pallof_press', 'cable_woodchop'),
('cable_woodchop', 'pallof_press', null),
('reverse_crunch', 'dead_bug', 'hanging_knee_raise'),
('hanging_knee_raise', 'reverse_crunch', null),
('farmer_carry', null, 'suitcase_carry'),
('suitcase_carry', 'farmer_carry', null),
('kb_goblet_carry', null, 'farmer_carry'),
('band_curl', null, 'db_biceps_curl'),
('db_biceps_curl', 'band_curl', 'barbell_curl'),
('hammer_curl', 'band_curl', null),
('cable_curl', 'band_curl', 'barbell_curl'),
('barbell_curl', 'db_biceps_curl', null),
('band_triceps_pushdown', null, 'cable_triceps_pushdown'),
('cable_triceps_pushdown', 'band_triceps_pushdown', 'db_overhead_triceps_extension'),
('db_overhead_triceps_extension', 'band_triceps_pushdown', 'db_skull_crusher'),
('db_skull_crusher', 'db_overhead_triceps_extension', null),
('bench_dip', null, null),
('band_lateral_raise', null, 'db_lateral_raise'),
('db_lateral_raise', 'band_lateral_raise', 'cable_lateral_raise'),
('cable_lateral_raise', 'db_lateral_raise', null),
('db_rear_delt_fly', 'band_pull_apart', null),
('db_chest_fly', null, 'cable_chest_fly'),
('cable_chest_fly', 'db_chest_fly', null),
('leg_extension', null, null),
('lying_leg_curl', 'glute_bridge', null),
('stability_ball_leg_curl', 'glute_bridge', 'lying_leg_curl'),
('calf_raise_bw', null, 'db_calf_raise'),
('db_calf_raise', 'calf_raise_bw', 'machine_calf_raise'),
('machine_calf_raise', 'db_calf_raise', null),
('band_lateral_walk', null, null),
('squat_jump', 'bodyweight_squat', 'box_jump'),
('box_jump', 'squat_jump', 'broad_jump'),
('broad_jump', 'squat_jump', null),
('lateral_bound', 'lateral_lunge_bw', null),
('plyo_push_up', 'push_up', null),
('med_ball_chest_pass', 'push_up', 'plyo_push_up'),
('med_ball_slam', null, null),
('med_ball_rotational_throw', 'cable_woodchop', null),
('push_press', 'barbell_overhead_press', null),
('hang_power_clean', 'kb_swing', null),
('cat_cow', null, null),
('worlds_greatest_stretch', null, null),
('hip_90_90', null, null),
('open_book', null, null),
('couch_stretch', null, null),
('childs_pose', null, null),
('ankle_rocks', null, null),
('deep_squat_hold', null, null),
('thread_the_needle', null, null),
('band_shoulder_pass', null, null),
('doorway_pec_stretch', null, null),
('supine_hamstring_stretch', null, null),
('figure_four_stretch', null, null),
('neck_cars', null, null)
) as l(slug, reg, prog) left join exercises r on r.slug = l.reg left join exercises p on p.slug = l.prog where e.slug = l.slug;

-- Food library (per 100 g)
insert into foods (slug, name, category, per_100g_cal, per_100g_protein, per_100g_carb, per_100g_fat, household_unit, household_g, household_portion_text, allergens, dietary_tags) values
('chicken_breast', 'Chicken breast, skinless, cooked', 'protein', 165, 31, 0, 3.6, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array[]::text[], array['gluten_free','dairy_free']::text[]),
('chicken_thigh', 'Chicken thigh, skinless, cooked', 'protein', 179, 24.8, 0, 8.2, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array[]::text[], array['gluten_free','dairy_free']::text[]),
('turkey_breast', 'Turkey breast, roasted', 'protein', 147, 30, 0, 2, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array[]::text[], array['gluten_free','dairy_free']::text[]),
('ground_turkey_93', 'Ground turkey 93% lean, cooked', 'protein', 213, 27, 0, 11.6, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array[]::text[], array['gluten_free','dairy_free']::text[]),
('ground_beef_93', 'Ground beef 93% lean, cooked', 'protein', 196, 26, 0, 10, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array[]::text[], array['gluten_free','dairy_free']::text[]),
('sirloin', 'Top sirloin steak, lean, cooked', 'protein', 183, 29, 0, 7, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array[]::text[], array['gluten_free','dairy_free']::text[]),
('pork_tenderloin', 'Pork tenderloin, cooked', 'protein', 143, 26, 0, 3.5, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array[]::text[], array['gluten_free','dairy_free']::text[]),
('salmon', 'Salmon, cooked', 'protein', 206, 22, 0, 12.4, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array['fish']::text[], array['pescatarian','gluten_free','dairy_free']::text[]),
('tuna_canned', 'Tuna, canned in water, drained', 'protein', 116, 26, 0, 1, 'oz drained', 28.35, '1 oz drained ≈ 28 g', array['fish']::text[], array['pescatarian','gluten_free','dairy_free']::text[]),
('cod', 'Cod, cooked', 'protein', 105, 23, 0, 0.9, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array['fish']::text[], array['pescatarian','gluten_free','dairy_free']::text[]),
('tilapia', 'Tilapia, cooked', 'protein', 128, 26, 0, 2.7, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array['fish']::text[], array['pescatarian','gluten_free','dairy_free']::text[]),
('shrimp', 'Shrimp, cooked', 'protein', 99, 24, 0.2, 0.3, 'oz cooked', 28.35, '1 oz cooked ≈ 28 g', array['shellfish']::text[], array['pescatarian','gluten_free','dairy_free']::text[]),
('sardines', 'Sardines, canned in oil, drained', 'protein', 208, 24.6, 0, 11.5, 'oz drained', 28.35, '1 oz drained ≈ 28 g', array['fish']::text[], array['pescatarian','gluten_free','dairy_free']::text[]),
('eggs', 'Eggs, whole', 'protein', 143, 12.6, 0.7, 9.5, 'large egg', 50, '1 large egg ≈ 50 g', array['egg']::text[], array['vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('egg_whites', 'Egg whites', 'protein', 52, 10.9, 0.7, 0.2, 'large egg white', 33, '1 large egg white ≈ 33 g', array['egg']::text[], array['vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('tofu_firm', 'Tofu, firm', 'protein', 144, 17.3, 2.8, 8.7, 'oz', 28.35, '1 oz ≈ 28 g', array['soy']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('tempeh', 'Tempeh', 'protein', 192, 20.3, 7.6, 10.8, 'oz', 28.35, '1 oz ≈ 28 g', array['soy']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('edamame', 'Edamame, shelled, cooked', 'protein', 121, 11.9, 8.9, 5.2, 'cup', 155, '1 cup ≈ 155 g', array['soy']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('seitan', 'Seitan', 'protein', 141, 25, 5, 2, 'oz', 28.35, '1 oz ≈ 28 g', array['wheat','gluten']::text[], array['vegan','vegetarian','pescatarian','dairy_free']::text[]),
('whey_protein', 'Whey protein powder', 'protein', 390, 80, 7, 5, 'scoop', 30, '1 scoop ≈ 30 g', array['milk']::text[], array['vegetarian','pescatarian','gluten_free']::text[]),
('pea_protein', 'Pea protein powder', 'protein', 380, 80, 4, 6, 'scoop', 30, '1 scoop ≈ 30 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('greek_yogurt_nonfat', 'Greek yogurt, plain, nonfat', 'dairy', 59, 10.2, 3.6, 0.4, 'cup', 245, '1 cup ≈ 245 g', array['milk']::text[], array['vegetarian','pescatarian','gluten_free']::text[]),
('cottage_cheese_2', 'Cottage cheese, 2%', 'dairy', 84, 11, 4.3, 2.3, 'cup', 226, '1 cup ≈ 226 g', array['milk']::text[], array['vegetarian','pescatarian','gluten_free']::text[]),
('mozzarella_part_skim', 'Mozzarella, part-skim (string cheese)', 'dairy', 254, 24.3, 2.8, 15.9, 'oz / stick', 28.35, '1 oz / stick ≈ 28 g', array['milk']::text[], array['vegetarian','pescatarian','gluten_free']::text[]),
('cheddar', 'Cheddar cheese', 'dairy', 403, 22.9, 3.1, 33.1, 'oz', 28.35, '1 oz ≈ 28 g', array['milk']::text[], array['vegetarian','pescatarian','gluten_free']::text[]),
('milk_1pct', 'Milk, 1%', 'dairy', 42, 3.4, 5, 1, 'cup', 244, '1 cup ≈ 244 g', array['milk']::text[], array['vegetarian','pescatarian','gluten_free']::text[]),
('milk_skim', 'Milk, skim', 'dairy', 34, 3.4, 5, 0.1, 'cup', 244, '1 cup ≈ 244 g', array['milk']::text[], array['vegetarian','pescatarian','gluten_free']::text[]),
('soy_milk', 'Soy milk, unsweetened', 'dairy', 33, 2.9, 1.7, 1.6, 'cup', 243, '1 cup ≈ 243 g', array['soy']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('oats', 'Rolled oats, dry', 'carb', 379, 13.2, 67.7, 6.5, 'cup dry', 81, '1 cup dry ≈ 81 g', array[]::text[], array['vegan','vegetarian','pescatarian','dairy_free']::text[]),
('white_rice', 'White rice, cooked', 'carb', 130, 2.7, 28.2, 0.3, 'cup cooked', 158, '1 cup cooked ≈ 158 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('brown_rice', 'Brown rice, cooked', 'carb', 123, 2.7, 25.6, 1, 'cup cooked', 202, '1 cup cooked ≈ 202 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('quinoa', 'Quinoa, cooked', 'carb', 120, 4.4, 21.3, 1.9, 'cup cooked', 185, '1 cup cooked ≈ 185 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('sweet_potato', 'Sweet potato, baked', 'carb', 90, 2, 20.7, 0.2, 'medium sweet potato', 150, '1 medium sweet potato ≈ 150 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('potato', 'Potato, baked with skin', 'carb', 93, 2.5, 21, 0.1, 'medium potato', 173, '1 medium potato ≈ 173 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('ww_bread', 'Whole-wheat bread', 'carb', 252, 12.4, 42.7, 3.5, 'slice', 32, '1 slice ≈ 32 g', array['wheat','gluten']::text[], array['vegan','vegetarian','pescatarian','dairy_free']::text[]),
('ww_pasta', 'Whole-wheat pasta, cooked', 'carb', 149, 5.8, 30, 1.7, 'cup cooked', 140, '1 cup cooked ≈ 140 g', array['wheat','gluten']::text[], array['vegan','vegetarian','pescatarian','dairy_free']::text[]),
('pasta', 'Pasta, cooked', 'carb', 158, 5.8, 30.9, 0.9, 'cup cooked', 140, '1 cup cooked ≈ 140 g', array['wheat','gluten']::text[], array['vegan','vegetarian','pescatarian','dairy_free']::text[]),
('corn_tortilla', 'Corn tortilla (6-inch)', 'carb', 218, 5.7, 44.6, 2.9, 'tortilla', 26, '1 tortilla ≈ 26 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('flour_tortilla', 'Flour tortilla (8-inch)', 'carb', 312, 8.3, 51.6, 8, 'tortilla', 45, '1 tortilla ≈ 45 g', array['wheat','gluten']::text[], array['vegan','vegetarian','pescatarian','dairy_free']::text[]),
('english_muffin', 'Whole-wheat English muffin', 'carb', 203, 8.8, 40, 2.1, 'muffin', 66, '1 muffin ≈ 66 g', array['wheat','gluten']::text[], array['vegan','vegetarian','pescatarian','dairy_free']::text[]),
('rice_cakes', 'Rice cakes, plain', 'carb', 387, 8.2, 81.5, 2.8, 'cake', 9, '1 cake ≈ 9 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('couscous', 'Couscous, cooked', 'carb', 112, 3.8, 23.2, 0.2, 'cup cooked', 157, '1 cup cooked ≈ 157 g', array['wheat','gluten']::text[], array['vegan','vegetarian','pescatarian','dairy_free']::text[]),
('barley', 'Pearled barley, cooked', 'carb', 123, 2.3, 28.2, 0.4, 'cup cooked', 157, '1 cup cooked ≈ 157 g', array['gluten']::text[], array['vegan','vegetarian','pescatarian','dairy_free']::text[]),
('lentils', 'Lentils, cooked', 'carb', 116, 9, 20.1, 0.4, 'cup cooked', 198, '1 cup cooked ≈ 198 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('black_beans', 'Black beans, cooked', 'carb', 132, 8.9, 23.7, 0.5, 'cup cooked', 172, '1 cup cooked ≈ 172 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('chickpeas', 'Chickpeas, cooked', 'carb', 164, 8.9, 27.4, 2.6, 'cup cooked', 164, '1 cup cooked ≈ 164 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('corn', 'Sweet corn kernels, cooked', 'carb', 96, 3.4, 21, 1.5, 'cup', 145, '1 cup ≈ 145 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('green_peas', 'Green peas, cooked', 'carb', 84, 5.4, 15.6, 0.2, 'cup', 160, '1 cup ≈ 160 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('banana', 'Banana', 'fruit', 89, 1.1, 22.8, 0.3, 'medium banana', 118, '1 medium banana ≈ 118 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('apple', 'Apple', 'fruit', 52, 0.3, 13.8, 0.2, 'medium apple', 182, '1 medium apple ≈ 182 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('blueberries', 'Blueberries', 'fruit', 57, 0.7, 14.5, 0.3, 'cup', 148, '1 cup ≈ 148 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('strawberries', 'Strawberries', 'fruit', 32, 0.7, 7.7, 0.3, 'cup', 152, '1 cup ≈ 152 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('orange', 'Orange', 'fruit', 47, 0.9, 11.8, 0.1, 'medium orange', 131, '1 medium orange ≈ 131 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('grapes', 'Grapes', 'fruit', 69, 0.7, 18.1, 0.2, 'cup', 151, '1 cup ≈ 151 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('pineapple', 'Pineapple chunks', 'fruit', 50, 0.5, 13.1, 0.1, 'cup', 165, '1 cup ≈ 165 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('raisins', 'Raisins', 'fruit', 299, 3.1, 79.2, 0.5, '¼-cup portion', 40, '1 ¼-cup portion ≈ 40 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('mango', 'Mango', 'fruit', 60, 0.8, 15, 0.4, 'cup', 165, '1 cup ≈ 165 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('pear', 'Pear', 'fruit', 57, 0.4, 15.2, 0.1, 'medium pear', 178, '1 medium pear ≈ 178 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('olive_oil', 'Olive oil', 'fat', 884, 0, 0, 100, 'tbsp', 13.5, '1 tbsp ≈ 14 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('avocado', 'Avocado', 'fat', 160, 2, 8.5, 14.7, 'medium avocado', 136, '1 medium avocado ≈ 136 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('almonds', 'Almonds', 'fat', 579, 21.2, 21.6, 49.9, 'oz (about 23)', 28.35, '1 oz (about 23) ≈ 28 g', array['tree_nut']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('walnuts', 'Walnuts', 'fat', 654, 15.2, 13.7, 65.2, 'oz', 28.35, '1 oz ≈ 28 g', array['tree_nut']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('cashews', 'Cashews', 'fat', 553, 18.2, 30.2, 43.9, 'oz', 28.35, '1 oz ≈ 28 g', array['tree_nut']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('peanut_butter', 'Peanut butter', 'fat', 588, 25, 20, 50, 'tbsp', 16, '1 tbsp ≈ 16 g', array['peanut']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('almond_butter', 'Almond butter', 'fat', 614, 21, 18.8, 55.5, 'tbsp', 16, '1 tbsp ≈ 16 g', array['tree_nut']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('chia_seeds', 'Chia seeds', 'fat', 486, 16.5, 42.1, 30.7, 'tbsp', 12, '1 tbsp ≈ 12 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('flaxseed', 'Ground flaxseed', 'fat', 534, 18.3, 28.9, 42.2, 'tbsp', 7, '1 tbsp ≈ 7 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('pumpkin_seeds', 'Pumpkin seeds', 'fat', 559, 30.2, 10.7, 49, 'oz', 28.35, '1 oz ≈ 28 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('sunflower_seeds', 'Sunflower seeds', 'fat', 584, 20.8, 20, 51.5, 'oz', 28.35, '1 oz ≈ 28 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('butter', 'Butter', 'fat', 717, 0.9, 0.1, 81.1, 'tbsp', 14.2, '1 tbsp ≈ 14 g', array['milk']::text[], array['vegetarian','pescatarian','gluten_free']::text[]),
('tahini', 'Tahini', 'fat', 595, 17, 21.2, 53.8, 'tbsp', 15, '1 tbsp ≈ 15 g', array['sesame']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('hummus', 'Hummus', 'fat', 166, 7.9, 14.3, 9.6, 'tbsp', 15, '1 tbsp ≈ 15 g', array['sesame']::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('olives', 'Olives', 'fat', 115, 0.8, 6, 10.7, 'large olive', 4.4, '1 large olive ≈ 4 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('dark_chocolate', 'Dark chocolate, 70–85%', 'fat', 598, 7.8, 45.9, 42.6, 'oz', 28.35, '1 oz ≈ 28 g', array['milk']::text[], array['vegetarian','pescatarian','gluten_free']::text[]),
('broccoli', 'Broccoli, cooked', 'vegetable', 35, 2.4, 7.2, 0.4, 'cup', 156, '1 cup ≈ 156 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('spinach', 'Spinach, raw', 'vegetable', 23, 2.9, 3.6, 0.4, 'cup', 30, '1 cup ≈ 30 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('romaine', 'Romaine lettuce', 'vegetable', 17, 1.2, 3.3, 0.3, 'cup shredded', 47, '1 cup shredded ≈ 47 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('green_beans', 'Green beans, cooked', 'vegetable', 35, 1.9, 7.9, 0.3, 'cup', 125, '1 cup ≈ 125 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('bell_pepper', 'Bell pepper, raw', 'vegetable', 26, 1, 6, 0.3, 'cup chopped', 149, '1 cup chopped ≈ 149 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('carrots', 'Carrots, raw', 'vegetable', 41, 0.9, 9.6, 0.2, 'cup chopped', 128, '1 cup chopped ≈ 128 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('cauliflower', 'Cauliflower, cooked', 'vegetable', 23, 1.8, 4.1, 0.5, 'cup', 124, '1 cup ≈ 124 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('zucchini', 'Zucchini, raw', 'vegetable', 17, 1.2, 3.1, 0.3, 'cup sliced', 113, '1 cup sliced ≈ 113 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('asparagus', 'Asparagus, cooked', 'vegetable', 22, 2.4, 4.1, 0.2, 'cup', 180, '1 cup ≈ 180 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('brussels_sprouts', 'Brussels sprouts, cooked', 'vegetable', 36, 2.6, 7.1, 0.5, 'cup', 156, '1 cup ≈ 156 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('tomato', 'Tomato', 'vegetable', 18, 0.9, 3.9, 0.2, 'medium tomato', 123, '1 medium tomato ≈ 123 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('cucumber', 'Cucumber', 'vegetable', 16, 0.7, 3.6, 0.1, 'cup sliced', 119, '1 cup sliced ≈ 119 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('mushrooms', 'Mushrooms, raw', 'vegetable', 22, 3.1, 3.3, 0.3, 'cup sliced', 70, '1 cup sliced ≈ 70 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('mixed_vegetables', 'Mixed vegetables (frozen), cooked', 'vegetable', 65, 2.9, 13.1, 0.2, 'cup', 182, '1 cup ≈ 182 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('onion', 'Onion', 'vegetable', 40, 1.1, 9.3, 0.1, 'medium onion', 110, '1 medium onion ≈ 110 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('salsa', 'Salsa', 'other', 36, 1.5, 7, 0.2, 'tbsp', 16, '1 tbsp ≈ 16 g', array[]::text[], array['vegan','vegetarian','pescatarian','gluten_free','dairy_free']::text[]),
('honey', 'Honey', 'other', 304, 0.3, 82.4, 0, 'tbsp', 21, '1 tbsp ≈ 21 g', array[]::text[], array['vegetarian','pescatarian','gluten_free','dairy_free']::text[])
on conflict (slug) do update set name = excluded.name, category = excluded.category, per_100g_cal = excluded.per_100g_cal, per_100g_protein = excluded.per_100g_protein, per_100g_carb = excluded.per_100g_carb, per_100g_fat = excluded.per_100g_fat, household_unit = excluded.household_unit, household_g = excluded.household_g, household_portion_text = excluded.household_portion_text, allergens = excluded.allergens, dietary_tags = excluded.dietary_tags;

-- Core / starter metrics (existing rows are left as you edited them)
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('weight_lb', 'Weight', 'number', 'lb', 'weekly', array['all']::text[], true, true, true, true, true, 10) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('adherence_pct', 'Adherence (weekly)', 'number', '%', 'weekly', array['all']::text[], true, true, true, true, true, 20) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('energy_1_10', 'Energy (avg)', 'scale_1_10', null, 'weekly', array['all']::text[], true, true, true, true, true, 30) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('sleep_hrs', 'Sleep (avg hrs)', 'number', 'hrs', 'weekly', array['all']::text[], true, true, true, true, false, 40) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('calories', 'Calories', 'number', 'kcal', 'daily', array['all']::text[], true, false, true, true, true, 50) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('protein_g', 'Protein', 'number', 'g', 'daily', array['all']::text[], true, false, true, true, true, 60) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('carbs_g', 'Carbs', 'number', 'g', 'daily', array['all']::text[], true, false, true, false, false, 70) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('fat_g', 'Fat', 'number', 'g', 'daily', array['all']::text[], true, false, true, false, false, 80) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('cardio_min', 'Cardio minutes', 'number', 'min', 'weekly', array['all']::text[], true, false, true, true, false, 90) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('steps', 'Steps (avg/day)', 'number', 'steps', 'weekly', array['all']::text[], true, false, true, true, false, 100) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('stress_1_10', 'Stress (avg)', 'scale_1_10', null, 'weekly', array['all']::text[], true, false, true, true, false, 110) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('soreness_1_10', 'Soreness', 'scale_1_10', null, 'weekly', array['all']::text[], false, false, true, true, false, 120) on conflict (key) do nothing;
insert into metric_definitions (key, label, type, unit, frequency, applies_to, is_core, required, active, show_in_charts, used_by_task_rule, display_order) values ('notes', 'Notes', 'text', null, 'ad_hoc', array['all']::text[], false, false, true, false, false, 130) on conflict (key) do nothing;

-- Default settings (existing values are kept)
insert into settings (key, value) values ('disclaimer', '"The nutrition targets and examples in this plan are estimates provided for educational purposes only. They are not medical advice and do not replace individualized guidance from a registered dietitian or physician. If you have a medical condition, are pregnant or breastfeeding, take medication, or have a history of disordered eating, consult a registered dietitian or physician before changing your diet."'::jsonb) on conflict (key) do nothing;
insert into settings (key, value) values ('task_thresholds', '{"outreachDays":7,"weighInMissingDays":8,"adherenceWindowDays":14,"adherenceLowPct":70,"energyLow":5,"strengthRetentionPct":95,"trainingGapDays":7,"clearanceFollowUpDays":7,"prospectFollowUpDays":5,"recheckWeeksAfterEnd":5,"weighInOverdueHour":12,"dailyDigest":false}'::jsonb) on conflict (key) do nothing;
insert into settings (key, value) values ('guardrail_limits', '{"minCalories":1200,"deficitMin":200,"deficitMax":500,"surplusMin":200,"surplusMax":500,"lossLbPerWeekMin":1,"lossLbPerWeekMax":2,"gainLbPerMonthMin":1,"gainLbPerMonthMax":2,"maintenanceBalanceMax":500,"proteinGPerLbMin":0.7,"proteinGPerLbMax":1,"proteinPctMin":10,"proteinPctMax":35,"carbPctMin":45,"carbPctMax":65,"carbPctMinWeightLoss":25,"fatPctMin":20,"fatPctMax":35,"fatPctBlocked":15,"waterFlOzMin":91,"waterFlOzMax":125,"waterFromFoodFraction":0.2}'::jsonb) on conflict (key) do nothing;
insert into settings (key, value) values ('default_deficits', '{"weight_loss":400,"muscle_gain":-300,"general_health":0,"performance":0}'::jsonb) on conflict (key) do nothing;
insert into settings (key, value) values ('uncertainty', '{"formula":0.1,"measured":0.12,"calibrated":0.05}'::jsonb) on conflict (key) do nothing;

commit;

select (select count(*) from exercises) as exercises, (select count(*) from foods) as foods, (select count(*) from metric_definitions) as metrics, (select count(*) from settings) as settings;
